import type { ContentItem, HeroItem } from "../domain/content-types";

export type MockHomepageData = {
  heroBanner: HeroItem[];
  continueWatching: ContentItem[];
  upcomingReleases: ContentItem[];
  hotMovies: ContentItem[];
  hotTvShows: ContentItem[];
  newAnime: ContentItem[];
  hotVariety: ContentItem[];
  hotShortDramas: ContentItem[];
};

export function getMockHomepageData(): MockHomepageData {
  return {
    heroBanner: [
      {
        id: "hero-1",
        title: "流浪地球2",
        description: "太阳即将毁灭，人类在地球表面建造出巨大的推进器，寻找新的家园。",
        backdropUrl: "https://via.placeholder.com/1920x1080/1a1a2e/ffffff?text=流浪地球2",
        rating: 8.3,
        type: "movie",
        trailerUrl: "https://example.com/trailer/wandering-earth-2",
      },
      {
        id: "hero-2",
        title: "三体",
        description: "地球文明向宇宙发出第一声啼鸣，取得了文明的联系，但也暴露了地球的坐标。",
        backdropUrl: "https://via.placeholder.com/1920x1080/16213e/ffffff?text=三体",
        rating: 8.7,
        type: "tv",
      },
      {
        id: "hero-3",
        title: "长安三万里",
        description: "盛唐时期，诗人高适与李白的传奇友谊和人生际遇。",
        backdropUrl: "https://via.placeholder.com/1920x1080/0f3460/ffffff?text=长安三万里",
        rating: 8.2,
        type: "movie",
      },
      {
        id: "hero-4",
        title: "狂飙",
        description: "一个普通人在时代洪流中的沉浮，以及正义与邪恶的较量。",
        backdropUrl: "https://via.placeholder.com/1920x1080/533483/ffffff?text=狂飙",
        rating: 9.1,
        type: "tv",
      },
      {
        id: "hero-5",
        title: "鬼灭之刃 锻刀村篇",
        description: "炭治郎前往锻刀村修复日轮刀，遭遇上弦之鬼的袭击。",
        backdropUrl: "https://via.placeholder.com/1920x1080/6a2c70/ffffff?text=鬼灭之刃",
        rating: 8.9,
        type: "anime",
      },
      {
        id: "hero-6",
        title: "漫长的季节",
        description: "一桩陈年旧案牵扯出三个家庭的命运纠葛。",
        backdropUrl: "https://via.placeholder.com/1920x1080/2d4059/ffffff?text=漫长的季节",
        rating: 9.4,
        type: "tv",
      },
    ],
    continueWatching: [
      {
        id: "cw-1",
        title: "繁城之下",
        coverUrl: "https://via.placeholder.com/300x450/1a1a2e/ffffff?text=繁城之下",
        rating: 8.1,
        year: 2024,
        type: "tv",
      },
      {
        id: "cw-2",
        title: "咒术回战 第二季",
        coverUrl: "https://via.placeholder.com/300x450/16213e/ffffff?text=咒术回战",
        rating: 8.8,
        year: 2023,
        type: "anime",
      },
      {
        id: "cw-3",
        title: "封神第一部",
        coverUrl: "https://via.placeholder.com/300x450/0f3460/ffffff?text=封神",
        rating: 7.8,
        year: 2023,
        type: "movie",
      },
      {
        id: "cw-4",
        title: "向往的生活 第七季",
        coverUrl: "https://via.placeholder.com/300x450/533483/ffffff?text=向往的生活",
        rating: 7.5,
        year: 2023,
        type: "variety",
      },
      {
        id: "cw-5",
        title: "无双",
        coverUrl: "https://via.placeholder.com/300x450/6a2c70/ffffff?text=无双",
        rating: 8.0,
        year: 2024,
        type: "shortdrama",
      },
    ],
    upcomingReleases: [
      {
        id: "ur-1",
        title: "流浪地球3",
        coverUrl: "https://via.placeholder.com/300x450/2d4059/ffffff?text=流浪地球3",
        year: 2026,
        type: "movie",
      },
      {
        id: "ur-2",
        title: "三体II：黑暗森林",
        coverUrl: "https://via.placeholder.com/300x450/1a1a2e/ffffff?text=三体II",
        year: 2026,
        type: "tv",
      },
      {
        id: "ur-3",
        title: "进击的巨人 最终季 完结篇",
        coverUrl: "https://via.placeholder.com/300x450/16213e/ffffff?text=进击的巨人",
        year: 2026,
        type: "anime",
      },
      {
        id: "ur-4",
        title: "奔跑吧 第十一季",
        coverUrl: "https://via.placeholder.com/300x450/0f3460/ffffff?text=奔跑吧",
        year: 2026,
        type: "variety",
      },
      {
        id: "ur-5",
        title: "长相思 第三季",
        coverUrl: "https://via.placeholder.com/300x450/533483/ffffff?text=长相思",
        year: 2026,
        type: "tv",
      },
      {
        id: "ur-6",
        title: "满江红",
        coverUrl: "https://via.placeholder.com/300x450/6a2c70/ffffff?text=满江红",
        year: 2026,
        type: "movie",
      },
    ],
    hotMovies: [
      {
        id: "hm-1",
        title: "消失的她",
        coverUrl: "https://via.placeholder.com/300x450/2d4059/ffffff?text=消失的她",
        rating: 7.6,
        year: 2023,
        type: "movie",
      },
      {
        id: "hm-2",
        title: "孤注一掷",
        coverUrl: "https://via.placeholder.com/300x450/1a1a2e/ffffff?text=孤注一掷",
        rating: 7.9,
        year: 2023,
        type: "movie",
      },
      {
        id: "hm-3",
        title: "八角笼中",
        coverUrl: "https://via.placeholder.com/300x450/16213e/ffffff?text=八角笼中",
        rating: 7.7,
        year: 2023,
        type: "movie",
      },
      {
        id: "hm-4",
        title: "热烈",
        coverUrl: "https://via.placeholder.com/300x450/0f3460/ffffff?text=热烈",
        rating: 7.4,
        year: 2023,
        type: "movie",
      },
      {
        id: "hm-5",
        title: "坚如磐石",
        coverUrl: "https://via.placeholder.com/300x450/533483/ffffff?text=坚如磐石",
        rating: 7.8,
        year: 2023,
        type: "movie",
      },
      {
        id: "hm-6",
        title: "前任4：英年早婚",
        coverUrl: "https://via.placeholder.com/300x450/6a2c70/ffffff?text=前任4",
        rating: 7.2,
        year: 2023,
        type: "movie",
      },
      {
        id: "hm-7",
        title: "第二十条",
        coverUrl: "https://via.placeholder.com/300x450/2d4059/ffffff?text=第二十条",
        rating: 8.0,
        year: 2024,
        type: "movie",
      },
      {
        id: "hm-8",
        title: "飞驰人生2",
        coverUrl: "https://via.placeholder.com/300x450/1a1a2e/ffffff?text=飞驰人生2",
        rating: 7.9,
        year: 2024,
        type: "movie",
      },
      {
        id: "hm-9",
        title: "热辣滚烫",
        coverUrl: "https://via.placeholder.com/300x450/16213e/ffffff?text=热辣滚烫",
        rating: 7.8,
        year: 2024,
        type: "movie",
      },
      {
        id: "hm-10",
        title: "周处除三害",
        coverUrl: "https://via.placeholder.com/300x450/0f3460/ffffff?text=周处除三害",
        rating: 8.4,
        year: 2024,
        type: "movie",
      },
      {
        id: "hm-11",
        title: "我们一起摇太阳",
        coverUrl: "https://via.placeholder.com/300x450/533483/ffffff?text=摇太阳",
        rating: 7.6,
        year: 2024,
        type: "movie",
      },
      {
        id: "hm-12",
        title: "功夫熊猫4",
        coverUrl: "https://via.placeholder.com/300x450/6a2c70/ffffff?text=功夫熊猫4",
        rating: 7.3,
        year: 2024,
        type: "movie",
      },
    ],
    hotTvShows: [
      {
        id: "ht-1",
        title: "繁花",
        coverUrl: "https://via.placeholder.com/300x450/2d4059/ffffff?text=繁花",
        rating: 8.1,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-2",
        title: "庆余年 第二季",
        coverUrl: "https://via.placeholder.com/300x450/1a1a2e/ffffff?text=庆余年2",
        rating: 8.5,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-3",
        title: "与凤行",
        coverUrl: "https://via.placeholder.com/300x450/16213e/ffffff?text=与凤行",
        rating: 7.8,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-4",
        title: "墨雨云间",
        coverUrl: "https://via.placeholder.com/300x450/0f3460/ffffff?text=墨雨云间",
        rating: 7.6,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-5",
        title: "玫瑰的故事",
        coverUrl: "https://via.placeholder.com/300x450/533483/ffffff?text=玫瑰的故事",
        rating: 7.9,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-6",
        title: "承欢记",
        coverUrl: "https://via.placeholder.com/300x450/6a2c70/ffffff?text=承欢记",
        rating: 7.7,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-7",
        title: "大奉打更人",
        coverUrl: "https://via.placeholder.com/300x450/2d4059/ffffff?text=大奉打更人",
        rating: 8.2,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-8",
        title: "南来北往",
        coverUrl: "https://via.placeholder.com/300x450/1a1a2e/ffffff?text=南来北往",
        rating: 8.0,
        year: 2024,
        type: "tv",
      },
    ],
    newAnime: [
      {
        id: "na-1",
        title: "葬送的芙莉莲",
        coverUrl: "https://via.placeholder.com/300x450/16213e/ffffff?text=芙莉莲",
        rating: 9.2,
        year: 2023,
        type: "anime",
      },
      {
        id: "na-2",
        title: "药屋少女的呢喃",
        coverUrl: "https://via.placeholder.com/300x450/0f3460/ffffff?text=药屋少女",
        rating: 8.7,
        year: 2023,
        type: "anime",
      },
      {
        id: "na-3",
        title: "间谍过家家 第二季",
        coverUrl: "https://via.placeholder.com/300x450/533483/ffffff?text=间谍过家家",
        rating: 8.5,
        year: 2023,
        type: "anime",
      },
      {
        id: "na-4",
        title: "我推的孩子",
        coverUrl: "https://via.placeholder.com/300x450/6a2c70/ffffff?text=我推的孩子",
        rating: 8.8,
        year: 2023,
        type: "anime",
      },
      {
        id: "na-5",
        title: "无职转生II",
        coverUrl: "https://via.placeholder.com/300x450/2d4059/ffffff?text=无职转生",
        rating: 8.6,
        year: 2023,
        type: "anime",
      },
      {
        id: "na-6",
        title: "转生成为第七王子",
        coverUrl: "https://via.placeholder.com/300x450/1a1a2e/ffffff?text=第七王子",
        rating: 7.9,
        year: 2024,
        type: "anime",
      },
      {
        id: "na-7",
        title: "怪兽8号",
        coverUrl: "https://via.placeholder.com/300x450/16213e/ffffff?text=怪兽8号",
        rating: 8.3,
        year: 2024,
        type: "anime",
      },
      {
        id: "na-8",
        title: "迷宫饭",
        coverUrl: "https://via.placeholder.com/300x450/0f3460/ffffff?text=迷宫饭",
        rating: 8.4,
        year: 2024,
        type: "anime",
      },
    ],
    hotVariety: [
      {
        id: "hv-1",
        title: "乘风2024",
        coverUrl: "https://via.placeholder.com/300x450/533483/ffffff?text=乘风2024",
        rating: 7.8,
        year: 2024,
        type: "variety",
      },
      {
        id: "hv-2",
        title: "歌手2024",
        coverUrl: "https://via.placeholder.com/300x450/6a2c70/ffffff?text=歌手2024",
        rating: 8.0,
        year: 2024,
        type: "variety",
      },
      {
        id: "hv-3",
        title: "种地吧",
        coverUrl: "https://via.placeholder.com/300x450/2d4059/ffffff?text=种地吧",
        rating: 7.9,
        year: 2024,
        type: "variety",
      },
      {
        id: "hv-4",
        title: "我们的客栈",
        coverUrl: "https://via.placeholder.com/300x450/1a1a2e/ffffff?text=我们的客栈",
        rating: 7.6,
        year: 2024,
        type: "variety",
      },
      {
        id: "hv-5",
        title: "声生不息·家年华",
        coverUrl: "https://via.placeholder.com/300x450/16213e/ffffff?text=声生不息",
        rating: 8.1,
        year: 2024,
        type: "variety",
      },
      {
        id: "hv-6",
        title: "五十公里桃花坞3",
        coverUrl: "https://via.placeholder.com/300x450/0f3460/ffffff?text=桃花坞",
        rating: 7.5,
        year: 2024,
        type: "variety",
      },
    ],
    hotShortDramas: [
      {
        id: "hs-1",
        title: "闪婚后大佬每天都在吃醋",
        coverUrl: "https://via.placeholder.com/300x450/533483/ffffff?text=闪婚",
        rating: 7.8,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-2",
        title: "夫人她马甲又轰动全城了",
        coverUrl: "https://via.placeholder.com/300x450/6a2c70/ffffff?text=夫人马甲",
        rating: 7.6,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-3",
        title: "重生后我成了首富",
        coverUrl: "https://via.placeholder.com/300x450/2d4059/ffffff?text=重生首富",
        rating: 7.9,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-4",
        title: "离婚后前夫跪求复合",
        coverUrl: "https://via.placeholder.com/300x450/1a1a2e/ffffff?text=离婚",
        rating: 7.5,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-5",
        title: "神医下山",
        coverUrl: "https://via.placeholder.com/300x450/16213e/ffffff?text=神医下山",
        rating: 7.7,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-6",
        title: "霸总的替身新娘",
        coverUrl: "https://via.placeholder.com/300x450/0f3460/ffffff?text=替身新娘",
        rating: 7.4,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-7",
        title: "穿越后我成了摄政王的心尖宠",
        coverUrl: "https://via.placeholder.com/300x450/533483/ffffff?text=摄政王",
        rating: 7.8,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-8",
        title: "豪门千金她不装了",
        coverUrl: "https://via.placeholder.com/300x450/6a2c70/ffffff?text=豪门千金",
        rating: 7.6,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-9",
        title: "退婚后我嫁给了京圈太子爷",
        coverUrl: "https://via.placeholder.com/300x450/2d4059/ffffff?text=太子爷",
        rating: 7.7,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-10",
        title: "全能大佬她又美又飒",
        coverUrl: "https://via.placeholder.com/300x450/1a1a2e/ffffff?text=全能大佬",
        rating: 7.5,
        year: 2024,
        type: "shortdrama",
      },
    ],
  };
}
