import type { ContentItem, HeroItem } from "../domain/content-types";
import { createPlaceholderImageUrl } from "@/shared/media/placeholder-image";

const mockImageUrl = (variant: "backdrop" | "poster", title: string, seed: string) =>
  createPlaceholderImageUrl({
    variant,
    fileStem: title,
    seed,
  });

const mockBackdropUrl = (title: string, seed: string) =>
  mockImageUrl("backdrop", title, seed);

const mockPosterUrl = (title: string, seed: string) =>
  mockImageUrl("poster", title, seed);

export type MockHomepageData = {
  heroBanner: HeroItem[];
  continueWatching: ContentItem[];
  upcomingReleases: ContentItem[];
  hotMovies: ContentItem[];
  hotTvShows: ContentItem[];
  newAnime: ContentItem[];
  hotVariety: ContentItem[];
  hotShortDramas: ContentItem[];
};

export function getMockHomepageData(): MockHomepageData {
  return {
    heroBanner: [
      {
        id: "hero-1",
        title: "流浪地球2",
        description: "太阳即将毁灭，人类在地球表面建造出巨大的推进器，寻找新的家园。",
        backdropUrl: mockBackdropUrl("流浪地球2", "1a1a2e"),
        rating: 8.3,
        type: "movie",
        trailerUrl: "https://example.com/trailer/wandering-earth-2",
      },
      {
        id: "hero-2",
        title: "三体",
        description: "地球文明向宇宙发出第一声啼鸣，取得了文明的联系，但也暴露了地球的坐标。",
        backdropUrl: mockBackdropUrl("三体", "16213e"),
        rating: 8.7,
        type: "tv",
      },
      {
        id: "hero-3",
        title: "长安三万里",
        description: "盛唐时期，诗人高适与李白的传奇友谊和人生际遇。",
        backdropUrl: mockBackdropUrl("长安三万里", "0f3460"),
        rating: 8.2,
        type: "movie",
      },
      {
        id: "hero-4",
        title: "狂飙",
        description: "一个普通人在时代洪流中的沉浮，以及正义与邪恶的较量。",
        backdropUrl: mockBackdropUrl("狂飙", "533483"),
        rating: 9.1,
        type: "tv",
      },
      {
        id: "hero-5",
        title: "鬼灭之刃 锻刀村篇",
        description: "炭治郎前往锻刀村修复日轮刀，遭遇上弦之鬼的袭击。",
        backdropUrl: mockBackdropUrl("鬼灭之刃", "6a2c70"),
        rating: 8.9,
        type: "anime",
      },
      {
        id: "hero-6",
        title: "漫长的季节",
        description: "一桩陈年旧案牵扯出三个家庭的命运纠葛。",
        backdropUrl: mockBackdropUrl("漫长的季节", "2d4059"),
        rating: 9.4,
        type: "tv",
      },
    ],
    continueWatching: [
      {
        id: "cw-1",
        title: "繁城之下",
        coverUrl: mockPosterUrl("繁城之下", "1a1a2e"),
        rating: 8.1,
        year: 2024,
        type: "tv",
        continueWatching: {
          currentEpisode: 12,
          latestEpisode: 16,
          sourceName: "腾讯视频",
          source: "txvideo",
        },
      },
      {
        id: "cw-2",
        title: "咒术回战 第二季",
        coverUrl: mockPosterUrl("咒术回战", "16213e"),
        rating: 8.8,
        year: 2023,
        type: "anime",
        continueWatching: {
          currentEpisode: 16,
          latestEpisode: 23,
          sourceName: "Bilibili",
          source: "bilibili",
        },
      },
      {
        id: "cw-3",
        title: "封神第一部",
        coverUrl: mockPosterUrl("封神", "0f3460"),
        rating: 7.8,
        year: 2023,
        type: "movie",
        continueWatching: {
          currentEpisode: 1,
          latestEpisode: 1,
          sourceName: "爱奇艺",
          source: "iqiyi",
        },
      },
      {
        id: "cw-4",
        title: "向往的生活 第七季",
        coverUrl: mockPosterUrl("向往的生活", "533483"),
        rating: 7.5,
        year: 2023,
        type: "variety",
        continueWatching: {
          currentEpisode: 8,
          latestEpisode: 12,
          sourceName: "芒果TV",
          source: "mgtv",
        },
      },
      {
        id: "cw-5",
        title: "无双",
        coverUrl: mockPosterUrl("无双", "6a2c70"),
        rating: 8.0,
        year: 2024,
        type: "shortdrama",
        continueWatching: {
          currentEpisode: 18,
          latestEpisode: 24,
          sourceName: "腾讯视频",
          source: "txvideo",
        },
      },
    ],
    upcomingReleases: [
      {
        id: "ur-1",
        title: "流浪地球3",
        coverUrl: mockPosterUrl("流浪地球3", "2d4059"),
        year: 2026,
        type: "movie",
      },
      {
        id: "ur-2",
        title: "三体II：黑暗森林",
        coverUrl: mockPosterUrl("三体II", "1a1a2e"),
        year: 2026,
        type: "tv",
      },
      {
        id: "ur-3",
        title: "进击的巨人 最终季 完结篇",
        coverUrl: mockPosterUrl("进击的巨人", "16213e"),
        year: 2026,
        type: "anime",
      },
      {
        id: "ur-4",
        title: "奔跑吧 第十一季",
        coverUrl: mockPosterUrl("奔跑吧", "0f3460"),
        year: 2026,
        type: "variety",
      },
      {
        id: "ur-5",
        title: "长相思 第三季",
        coverUrl: mockPosterUrl("长相思", "533483"),
        year: 2026,
        type: "tv",
      },
      {
        id: "ur-6",
        title: "满江红",
        coverUrl: mockPosterUrl("满江红", "6a2c70"),
        year: 2026,
        type: "movie",
      },
    ],
    hotMovies: [
      {
        id: "hm-1",
        title: "消失的她",
        coverUrl: mockPosterUrl("消失的她", "2d4059"),
        rating: 7.6,
        year: 2023,
        type: "movie",
      },
      {
        id: "hm-2",
        title: "孤注一掷",
        coverUrl: mockPosterUrl("孤注一掷", "1a1a2e"),
        rating: 7.9,
        year: 2023,
        type: "movie",
      },
      {
        id: "hm-3",
        title: "八角笼中",
        coverUrl: mockPosterUrl("八角笼中", "16213e"),
        rating: 7.7,
        year: 2023,
        type: "movie",
      },
      {
        id: "hm-4",
        title: "热烈",
        coverUrl: mockPosterUrl("热烈", "0f3460"),
        rating: 7.4,
        year: 2023,
        type: "movie",
      },
      {
        id: "hm-5",
        title: "坚如磐石",
        coverUrl: mockPosterUrl("坚如磐石", "533483"),
        rating: 7.8,
        year: 2023,
        type: "movie",
      },
      {
        id: "hm-6",
        title: "前任4：英年早婚",
        coverUrl: mockPosterUrl("前任4", "6a2c70"),
        rating: 7.2,
        year: 2023,
        type: "movie",
      },
      {
        id: "hm-7",
        title: "第二十条",
        coverUrl: mockPosterUrl("第二十条", "2d4059"),
        rating: 8.0,
        year: 2024,
        type: "movie",
      },
      {
        id: "hm-8",
        title: "飞驰人生2",
        coverUrl: mockPosterUrl("飞驰人生2", "1a1a2e"),
        rating: 7.9,
        year: 2024,
        type: "movie",
      },
      {
        id: "hm-9",
        title: "热辣滚烫",
        coverUrl: mockPosterUrl("热辣滚烫", "16213e"),
        rating: 7.8,
        year: 2024,
        type: "movie",
      },
      {
        id: "hm-10",
        title: "周处除三害",
        coverUrl: mockPosterUrl("周处除三害", "0f3460"),
        rating: 8.4,
        year: 2024,
        type: "movie",
      },
      {
        id: "hm-11",
        title: "我们一起摇太阳",
        coverUrl: mockPosterUrl("摇太阳", "533483"),
        rating: 7.6,
        year: 2024,
        type: "movie",
      },
      {
        id: "hm-12",
        title: "功夫熊猫4",
        coverUrl: mockPosterUrl("功夫熊猫4", "6a2c70"),
        rating: 7.3,
        year: 2024,
        type: "movie",
      },
    ],
    hotTvShows: [
      {
        id: "ht-1",
        title: "繁花",
        coverUrl: mockPosterUrl("繁花", "2d4059"),
        rating: 8.1,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-2",
        title: "庆余年 第二季",
        coverUrl: mockPosterUrl("庆余年2", "1a1a2e"),
        rating: 8.5,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-3",
        title: "与凤行",
        coverUrl: mockPosterUrl("与凤行", "16213e"),
        rating: 7.8,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-4",
        title: "墨雨云间",
        coverUrl: mockPosterUrl("墨雨云间", "0f3460"),
        rating: 7.6,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-5",
        title: "玫瑰的故事",
        coverUrl: mockPosterUrl("玫瑰的故事", "533483"),
        rating: 7.9,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-6",
        title: "承欢记",
        coverUrl: mockPosterUrl("承欢记", "6a2c70"),
        rating: 7.7,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-7",
        title: "大奉打更人",
        coverUrl: mockPosterUrl("大奉打更人", "2d4059"),
        rating: 8.2,
        year: 2024,
        type: "tv",
      },
      {
        id: "ht-8",
        title: "南来北往",
        coverUrl: mockPosterUrl("南来北往", "1a1a2e"),
        rating: 8.0,
        year: 2024,
        type: "tv",
      },
    ],
    newAnime: [
      {
        id: "na-1",
        title: "葬送的芙莉莲",
        coverUrl: mockPosterUrl("芙莉莲", "16213e"),
        rating: 9.2,
        year: 2023,
        type: "anime",
      },
      {
        id: "na-2",
        title: "药屋少女的呢喃",
        coverUrl: mockPosterUrl("药屋少女", "0f3460"),
        rating: 8.7,
        year: 2023,
        type: "anime",
      },
      {
        id: "na-3",
        title: "间谍过家家 第二季",
        coverUrl: mockPosterUrl("间谍过家家", "533483"),
        rating: 8.5,
        year: 2023,
        type: "anime",
      },
      {
        id: "na-4",
        title: "我推的孩子",
        coverUrl: mockPosterUrl("我推的孩子", "6a2c70"),
        rating: 8.8,
        year: 2023,
        type: "anime",
      },
      {
        id: "na-5",
        title: "无职转生II",
        coverUrl: mockPosterUrl("无职转生", "2d4059"),
        rating: 8.6,
        year: 2023,
        type: "anime",
      },
      {
        id: "na-6",
        title: "转生成为第七王子",
        coverUrl: mockPosterUrl("第七王子", "1a1a2e"),
        rating: 7.9,
        year: 2024,
        type: "anime",
      },
      {
        id: "na-7",
        title: "怪兽8号",
        coverUrl: mockPosterUrl("怪兽8号", "16213e"),
        rating: 8.3,
        year: 2024,
        type: "anime",
      },
      {
        id: "na-8",
        title: "迷宫饭",
        coverUrl: mockPosterUrl("迷宫饭", "0f3460"),
        rating: 8.4,
        year: 2024,
        type: "anime",
      },
    ],
    hotVariety: [
      {
        id: "hv-1",
        title: "乘风2024",
        coverUrl: mockPosterUrl("乘风2024", "533483"),
        rating: 7.8,
        year: 2024,
        type: "variety",
      },
      {
        id: "hv-2",
        title: "歌手2024",
        coverUrl: mockPosterUrl("歌手2024", "6a2c70"),
        rating: 8.0,
        year: 2024,
        type: "variety",
      },
      {
        id: "hv-3",
        title: "种地吧",
        coverUrl: mockPosterUrl("种地吧", "2d4059"),
        rating: 7.9,
        year: 2024,
        type: "variety",
      },
      {
        id: "hv-4",
        title: "我们的客栈",
        coverUrl: mockPosterUrl("我们的客栈", "1a1a2e"),
        rating: 7.6,
        year: 2024,
        type: "variety",
      },
      {
        id: "hv-5",
        title: "声生不息·家年华",
        coverUrl: mockPosterUrl("声生不息", "16213e"),
        rating: 8.1,
        year: 2024,
        type: "variety",
      },
      {
        id: "hv-6",
        title: "五十公里桃花坞3",
        coverUrl: mockPosterUrl("桃花坞", "0f3460"),
        rating: 7.5,
        year: 2024,
        type: "variety",
      },
    ],
    hotShortDramas: [
      {
        id: "hs-1",
        title: "闪婚后大佬每天都在吃醋",
        coverUrl: mockPosterUrl("闪婚", "533483"),
        rating: 7.8,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-2",
        title: "夫人她马甲又轰动全城了",
        coverUrl: mockPosterUrl("夫人马甲", "6a2c70"),
        rating: 7.6,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-3",
        title: "重生后我成了首富",
        coverUrl: mockPosterUrl("重生首富", "2d4059"),
        rating: 7.9,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-4",
        title: "离婚后前夫跪求复合",
        coverUrl: mockPosterUrl("离婚", "1a1a2e"),
        rating: 7.5,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-5",
        title: "神医下山",
        coverUrl: mockPosterUrl("神医下山", "16213e"),
        rating: 7.7,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-6",
        title: "霸总的替身新娘",
        coverUrl: mockPosterUrl("替身新娘", "0f3460"),
        rating: 7.4,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-7",
        title: "穿越后我成了摄政王的心尖宠",
        coverUrl: mockPosterUrl("摄政王", "533483"),
        rating: 7.8,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-8",
        title: "豪门千金她不装了",
        coverUrl: mockPosterUrl("豪门千金", "6a2c70"),
        rating: 7.6,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-9",
        title: "退婚后我嫁给了京圈太子爷",
        coverUrl: mockPosterUrl("太子爷", "2d4059"),
        rating: 7.7,
        year: 2024,
        type: "shortdrama",
      },
      {
        id: "hs-10",
        title: "全能大佬她又美又飒",
        coverUrl: mockPosterUrl("全能大佬", "1a1a2e"),
        rating: 7.5,
        year: 2024,
        type: "shortdrama",
      },
    ],
  };
}
